export const dlr = [
    { name: 'Abbey Road', zone: '2/3' },
    { name: 'All Saints', zone: '2' },
    { name: 'Bank', zone: '1' },
    { name: 'Beckton', zone: '3' },
    { name: 'Beckton Park', zone: '3' },
    { name: 'Blackwall', zone: '2' },
    { name: 'Bow Church', zone: '2' },
    { name: 'Canning Town', zone: '2/3' },
    { name: 'Canary Wharf', zone: '2' },
    { name: 'Crossharbour', zone: '2' },
    { name: 'Custom House', zone: '3' },
    { name: 'Cyprus', zone: '3' },
    { name: 'Deptford Bridge', zone: '2/3' },
    { name: 'Devons Road', zone: '2' },
    { name: 'East India', zone: '2/3' },
    { name: 'Elverson Road', zone: '2/3' },
    { name: 'Gallions Reach', zone: '3' },
    { name: 'Greenwich', zone: '2/3' },
    { name: 'Heron Quays', zone: '2' },
    { name: 'Island Gardens', zone: '2' },
    { name: 'King George V', zone: '3' },
    { name: 'Langdon Park', zone: '2' },
    { name: 'Lewisham', zone: '2/3' },
    { name: 'Limehouse', zone: '2' },
    { name: 'London City Airport', zone: '3' },
    { name: 'Mudchute', zone: '2' },
    { name: 'Pontoon Dock', zone: '3' },
    { name: 'Poplar', zone: '2' },
    { name: 'Prince Regent', zone: '3' },
    { name: 'Pudding Mill Lane', zone: '2/3' },
    { name: 'Royal Albert', zone: '3' },
    { name: 'Royal Victoria', zone: '3' },
    { name: 'Shadwell', zone: '2' },
    { name: 'South Quay', zone: '2' },
    { name: 'Star Lane', zone: '2/3' },
    { name: 'Stratford', zone: '2/3' },
    { name: 'Stratford High Street', zone: '2/3' },
    { name: 'Stratford International', zone: '2/3' },
    { name: 'Tower Gateway', zone: '1' },
    { name: 'West India Quay', zone: '2' },
    { name: 'West Silvertown', zone: '3' },
    { name: 'Westferry', zone: '2' },
    { name: 'Woolwich Arsenal', zone: '3/4' },
];
