export const overground = [
    { name: 'Acton Central', zone: '2' },
    { name: 'Anerley', zone: '4' },
    { name: 'Barking', zone: '4' },
    { name: 'Battersea Park', zone: '2' },
    { name: 'Bethnal Green', zone: '2' },
    { name: 'Blackhorse Road', zone: '3' },
    { name: 'Brockley', zone: '2' },
    { name: 'Brondesbury', zone: '2' },
    { name: 'Brondesbury Park', zone: '2' },
    { name: 'Bruce Grove', zone: '3' },
    { name: 'Bush Hill Park', zone: '5' },
    { name: 'Bushey', zone: '8' },
    { name: 'Cambridge Heath', zone: '2' },
    { name: 'Camden Road', zone: '2' },
    { name: 'Canonbury', zone: '2' },
    { name: 'Carpenders Park', zone: '7' },
    { name: 'Caledonian Road & Barnsbury', zone: '2' },
    { name: 'Cheshunt', zone: '8' },
    { name: 'Chingford', zone: '5' },
    { name: 'Clapham High Street', zone: '2' },
    { name: 'Clapham Junction', zone: '2' },
    { name: 'Clapton', zone: '2/3' },
    { name: 'Crystal Palace', zone: '3/4' },
    { name: 'Dalston Junction', zone: '2' },
    { name: 'Dalston Kingsland', zone: '2' },
    { name: 'Denmark Hill', zone: '2' },
    { name: 'Edmonton Green', zone: '4' },
    { name: 'Emerson Park', zone: '6' },
    { name: 'Enfield Town', zone: '5' },
    { name: 'Euston', zone: '1' },
    { name: 'Finchley Road & Frognal', zone: '2' },
    { name: 'Forest Hill', zone: '3' },
    { name: 'Gospel Oak', zone: '2' },
    { name: 'Gunnersbury', zone: '3' },
    { name: 'Hackney Central', zone: '2' },
    { name: 'Hackney Downs', zone: '2' },
    { name: 'Hackney Wick', zone: '2' },
    { name: 'Haggerston', zone: '2' },
    { name: 'Hampstead Heath', zone: '2/3' },
    { name: 'Harlesden', zone: '3' },
    { name: 'Harringay Green Lanes', zone: '3' },
    { name: 'Hatch End', zone: '6' },
    { name: 'Headstone Lane', zone: '5' },
    { name: 'Highbury & Islington', zone: '2' },
    { name: 'Homerton', zone: '2' },
    { name: 'Honor Oak Park', zone: '3' },
    { name: 'Hoxton', zone: '1/2' },
    { name: 'Imperial Wharf', zone: '2' },
    { name: 'Kensal Green', zone: '2' },
    { name: 'Kensal Rise', zone: '2' },
    { name: 'Kensington (Olympia)', zone: '2' },
    { name: 'Kentish Town West', zone: '2' },
    { name: 'Kew Gardens', zone: '3/4' },
    { name: 'Kilburn High Road', zone: '2' },
    { name: 'Leyton Midland Road', zone: '3' },
    { name: 'Leytonstone High Road', zone: '3' },
    { name: 'London Fields', zone: '2' },
    { name: 'New Cross', zone: '2' },
    { name: 'New Cross Gate', zone: '2' },
    { name: 'Norwood Junction', zone: '4' },
    { name: 'Peckham Rye', zone: '2' },
    { name: 'Penge West', zone: '4' },
    { name: 'Queens Road Peckham', zone: '2' },
    { name: 'Rectory Road', zone: '2' },
    { name: 'Richmond', zone: '4' },
    { name: 'Romford', zone: '6' },
    { name: 'Rotherhithe', zone: '2' },
    { name: 'Seven Sisters', zone: '3' },
    { name: 'Shadwell', zone: '2' },
    { name: "Shepherd's Bush", zone: '2' },
    { name: 'Shoreditch High Street', zone: '1' },
    { name: 'Silver Street', zone: '4' },
    { name: 'South Acton', zone: '3' },
    { name: 'South Hampstead', zone: '2' },
    { name: 'South Tottenham', zone: '3' },
    { name: 'Southbury', zone: '5' },
    { name: 'St James Street', zone: '3' },
    { name: 'Stamford Hill', zone: '3' },
    { name: 'Stoke Newington', zone: '2' },
    { name: 'Stonebridge Park', zone: '3' },
    { name: 'Stratford', zone: '2/3' },
    { name: 'Surrey Quays', zone: '2' },
    { name: 'Sydenham', zone: '3' },
    { name: 'Theobalds Grove', zone: '7' },
    { name: 'Turkey Street', zone: '6' },
    { name: 'Upper Holloway', zone: '2' },
    { name: 'Walthamstow Central', zone: '3' },
    { name: "Walthamstow Queen's Road", zone: '3' },
    { name: 'Wandsworth Road', zone: '2' },
    { name: 'Wanstead Park', zone: '3' },
    { name: 'Watford High Street', zone: '8' },
    { name: 'Watford Junction', zone: 'Special' },
    { name: 'West Brompton', zone: '2' },
    { name: 'West Croydon', zone: '5' },
    { name: 'West Hampstead', zone: '2' },
    { name: 'White Hart Lane', zone: '3' },
    { name: 'Whitechapel', zone: '2' },
    { name: 'Wembley Central', zone: '4' },
    { name: 'Willesden Junction', zone: '2/3' },
    { name: 'Wood Street', zone: '4' },
    { name: 'Woodgrange Park', zone: '3/4' },
];
