export const trams = [
    { name: 'Addiscombe', zone: '3/4' },
    { name: 'Addington Village', zone: '4' },
    { name: 'Ampere Way', zone: '4' },
    { name: 'Arena', zone: '5' },
    { name: 'Avenue Road', zone: '5/6' },
    { name: 'Becketts Farm', zone: '4' },
    { name: 'Belgrave Walk', zone: '4' },
    { name: 'Birkbeck', zone: '4' },
    { name: 'Blackhorse Lane', zone: '3' },
    { name: 'Centrale', zone: '3/4' },
    { name: 'Church Street', zone: '3/4' },
    { name: 'Coombe Lane', zone: '5' },
    { name: 'Dundonald Road', zone: '3' },
    { name: 'East Croydon', zone: '5' },
    { name: 'Elmers End', zone: '4' },
    { name: 'Fieldway', zone: '4' },
    { name: 'George Street', zone: '3/4' },
    { name: 'Gravel Hill', zone: '4' },
    { name: 'Harrington Road', zone: '3' },
    { name: "King Henry's Drive", zone: '4' },
    { name: 'Lebanon Road', zone: '3/4' },
    { name: 'Lloyd Park', zone: '4' },
    { name: 'Merton Park', zone: '3' },
    { name: 'Mitcham', zone: '3' },
    { name: 'Mitcham Junction', zone: '4' },
    { name: 'Morden Road', zone: '3' },
    { name: 'New Addington', zone: '4' },
    { name: 'Phipps Bridge', zone: '3' },
    { name: 'Reeves Corner', zone: '3/4' },
    { name: 'Sandilands', zone: '3/4' },
    { name: 'Therapia Lane', zone: '4' },
    { name: 'Waddon Marsh', zone: '4' },
    { name: 'Wandle Park', zone: '3/4' },
    { name: 'Wellesley Road', zone: '3/4' },
    { name: 'West Croydon', zone: '3/4' },
    { name: 'Woodside', zone: '4' },
];
