export const underground = [
    { name: 'Harrow & Wealdstone', zone: '5' },
    { name: 'Kenton', zone: '4' },
    { name: 'South Kenton', zone: '4' },
    { name: 'North Wembley', zone: '4' },
    { name: 'Wembley Central', zone: '4' },
    { name: 'Stonebridge Park', zone: '3' },
    { name: 'Harlesden', zone: '3' },
    { name: 'Willesden Junction', zone: '2/3' },
    { name: 'Kensal Green', zone: '2' },
    { name: "Queen's Park", zone: '2' },
    { name: 'Kilburn Park', zone: '2' },
    { name: 'Maida Vale', zone: '2' },
    { name: 'Warwick Avenue', zone: '2' },
    { name: 'Paddington', zone: '1' },
    { name: 'Edgware Road', zone: '1' },
    { name: 'Marylebone', zone: '1' },
    { name: 'Baker Street', zone: '1' },
    { name: "Regent's Park", zone: '1' },
    { name: 'Oxford Circus', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Lambeth North', zone: '1' },
    { name: 'Elephant & Castle', zone: '1/2' },
    { name: 'Ealing Broadway', zone: '3' },
    { name: 'Ealing Common', zone: '3' },
    { name: 'Acton Town', zone: '3' },
    { name: 'White City', zone: '2' },
    { name: 'Holland Park', zone: '2' },
    { name: 'Notting Hill Gate', zone: '1/2' },
    { name: 'Queensway', zone: '1' },
    { name: 'Lancaster Gate', zone: '1' },
    { name: 'Marble Arch', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Oxford Circus', zone: '1' },
    { name: 'Tottenham Court Road', zone: '1' },
    { name: 'Holborn', zone: '1' },
    { name: 'Chancery Lane', zone: '1' },
    { name: "St. Paul's", zone: '1' },
    { name: 'Bank', zone: '1' },
    { name: 'Liverpool Street', zone: '1' },
    { name: "St. James's Park", zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Blackfriars', zone: '1' },
    { name: 'Temple', zone: '1' },
    { name: 'Chancery Lane', zone: '1' },
    { name: 'Holborn', zone: '1' },
    { name: 'Tottenham Court Road', zone: '1' },
    { name: 'Oxford Circus', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Marble Arch', zone: '1' },
    { name: 'Lancaster Gate', zone: '1' },
    { name: 'Queensway', zone: '1' },
    { name: 'Notting Hill Gate', zone: '1/2' },
    { name: 'Holland Park', zone: '2' },
    { name: 'White City', zone: '2' },
    { name: 'Acton Town', zone: '3' },
    { name: 'Ealing Common', zone: '3' },
    { name: 'Ealing Broadway', zone: '3' },
    { name: 'North Acton', zone: '2/3' },
    { name: 'Hanger Lane', zone: '3' },
    { name: 'Park Royal', zone: '3' },
    { name: 'Northfields', zone: '3' },
    { name: 'East Acton', zone: '2' },
    { name: 'White City', zone: '2' },
    { name: 'Stanmore', zone: '5' },
    { name: 'Canons Park', zone: '5' },
    { name: 'Kingsbury', zone: '4' },
    { name: 'Queensbury', zone: '4' },
    { name: 'Kilburn Park', zone: '2' },
    { name: 'West Hampstead', zone: '2' },
    { name: 'Finchley Road', zone: '2' },
    { name: 'Baker Street', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Southwark', zone: '1' },
    { name: 'London Bridge', zone: '1' },
    { name: 'Bermondsey', zone: '2' },
    { name: 'Canada Water', zone: '2' },
    { name: 'Canary Wharf', zone: '2' },
    { name: 'North Greenwich', zone: '2/3' },
    { name: 'Greenwich', zone: '2/3' },
    { name: 'Canary Wharf', zone: '2' },
    { name: 'Canada Water', zone: '2' },
    { name: 'Bermondsey', zone: '2' },
    { name: 'London Bridge', zone: '1' },
    { name: 'Southwark', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Baker Street', zone: '1' },
    { name: 'Finchley Road', zone: '2' },
    { name: 'West Hampstead', zone: '2' },
    { name: 'Kilburn Park', zone: '2' },
    { name: 'Queensbury', zone: '4' },
    { name: 'Kingsbury', zone: '4' },
    { name: 'Canons Park', zone: '5' },
    { name: 'Stanmore', zone: '5' },
    { name: 'Victoria', zone: '1' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Brixton', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Clapham North', zone: '2' },
    { name: 'Clapham Common', zone: '2' },
    { name: 'Clapham South', zone: '2/3' },
    { name: 'Balham', zone: '3' },
    { name: 'Tooting Bec', zone: '3' },
    { name: 'Tooting Broadway', zone: '3' },
    { name: 'Colliers Wood', zone: '3' },
    { name: 'South Wimbledon', zone: '3/4' },
    { name: 'Morden', zone: '4' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Barons Court', zone: '2' },
    { name: 'Kensington (Olympia)', zone: '2' },
    { name: 'High Street Kensington', zone: '1' },
    { name: 'Gloucester Road', zone: '1' },
    { name: 'South Kensington', zone: '1' },
    { name: 'Sloane Square', zone: '1' },
    { name: 'Knightsbridge', zone: '1' },
    { name: 'Hyde Park Corner', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Oxford Circus', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Baker Street', zone: '1' },
    { name: 'Edgware Road', zone: '1' },
    { name: 'Marylebone', zone: '1' },
    { name: 'Paddington', zone: '1' },
    { name: 'Edgware Road', zone: '1' },
    { name: 'Baker Street', zone: '1' },
    { name: "Regent's Park", zone: '1' },
    { name: 'Oxford Circus', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: "St. James's Park", zone: '1' },
    { name: 'Victoria', zone: '1' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Clapham North', zone: '2' },
    { name: 'Clapham Common', zone: '2' },
    { name: 'Clapham South', zone: '2/3' },
    { name: 'Balham', zone: '3' },
    { name: 'Tooting Bec', zone: '3' },
    { name: 'Tooting Broadway', zone: '3' },
    { name: 'Colliers Wood', zone: '3' },
    { name: 'South Wimbledon', zone: '3/4' },
    { name: 'Morden', zone: '4' },
    { name: 'Wimbledon Park', zone: '3' },
    { name: 'Wimbledon', zone: '3' },
    { name: 'Putney Bridge', zone: '2' },
    { name: 'East Putney', zone: '2/3' },
    { name: 'Putney Bridge', zone: '2' },
    { name: 'Parsons Green', zone: '2' },
    { name: 'Fulham Broadway', zone: '2' },
    { name: 'West Brompton', zone: '2' },
    { name: 'Earls Court', zone: '1/2' },
    { name: 'High Street Kensington', zone: '1' },
    { name: 'Kensington (Olympia)', zone: '2' },
    { name: 'Barons Court', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Ravenscourt Park', zone: '2' },
    { name: 'Goldhawk Road', zone: '2' },
    { name: "Shepherd's Bush Market", zone: '2' },
    { name: "Shepherd's Bush", zone: '2' },
    { name: 'Holland Park', zone: '2' },
    { name: 'Royal Oak', zone: '2' },
    { name: 'Westbourne Park', zone: '2' },
    { name: 'Ladbroke Grove', zone: '2' },
    { name: 'Latimer Road', zone: '2' },
    { name: 'Notting Hill Gate', zone: '1/2' },
    { name: 'High Street Kensington', zone: '1' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Ravenscourt Park', zone: '2' },
    { name: 'Goldhawk Road', zone: '2' },
    { name: "Shepherd's Bush Market", zone: '2' },
    { name: "Shepherd's Bush", zone: '2' },
    { name: 'Holland Park', zone: '2' },
    { name: 'Royal Oak', zone: '2' },
    { name: 'Westbourne Park', zone: '2' },
    { name: 'Ladbroke Grove', zone: '2' },
    { name: 'Latimer Road', zone: '2' },
    { name: 'Notting Hill Gate', zone: '1/2' },
    { name: "Queen's Road", zone: '1' },
    { name: 'Bayswater', zone: '1' },
    { name: 'Notting Hill Gate', zone: '1/2' },
    { name: 'Royal Oak', zone: '2' },
    { name: 'Westbourne Park', zone: '2' },
    { name: 'Ladbroke Grove', zone: '2' },
    { name: 'Latimer Road', zone: '2' },
    { name: 'Wood Lane', zone: '2' },
    { name: 'Latimer Road', zone: '2' },
    { name: 'Ladbroke Grove', zone: '2' },
    { name: 'Westbourne Park', zone: '2' },
    { name: 'Royal Oak', zone: '2' },
    { name: 'Holland Park', zone: '2' },
    { name: "Shepherd's Bush", zone: '2' },
    { name: "Shepherd's Bush Market", zone: '2' },
    { name: 'Goldhawk Road', zone: '2' },
    { name: 'Ravenscourt Park', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Fulham Broadway', zone: '2' },
    { name: 'Barons Court', zone: '2' },
    { name: 'Earls Court', zone: '1/2' },
    { name: 'Kensington (Olympia)', zone: '2' },
    { name: 'High Street Kensington', zone: '1' },
    { name: 'Gloucester Road', zone: '1' },
    { name: 'South Kensington', zone: '1' },
    { name: 'Sloane Square', zone: '1' },
    { name: 'Knightsbridge', zone: '1' },
    { name: 'Hyde Park Corner', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Oxford Circus', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Baker Street', zone: '1' },
    { name: 'Edgware Road', zone: '1' },
    { name: 'Marylebone', zone: '1' },
    { name: 'Paddington', zone: '1' },
    { name: 'Edgware Road', zone: '1' },
    { name: 'Baker Street', zone: '1' },
    { name: "Regent's Park", zone: '1' },
    { name: 'Oxford Circus', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: "St. James's Park", zone: '1' },
    { name: 'Victoria', zone: '1' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Clapham North', zone: '2' },
    { name: 'Clapham Common', zone: '2' },
    { name: 'Clapham South', zone: '2/3' },
    { name: 'Balham', zone: '3' },
    { name: 'Tooting Bec', zone: '3' },
    { name: 'Tooting Broadway', zone: '3' },
    { name: 'Colliers Wood', zone: '3' },
    { name: 'South Wimbledon', zone: '3/4' },
    { name: 'Morden', zone: '4' },
    { name: 'Wimbledon Park', zone: '3' },
    { name: 'Wimbledon', zone: '3' },
    { name: 'Putney Bridge', zone: '2' },
    { name: 'East Putney', zone: '2/3' },
    { name: 'Putney Bridge', zone: '2' },
    { name: 'Parsons Green', zone: '2' },
    { name: 'Fulham Broadway', zone: '2' },
    { name: 'Barons Court', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Aldgate East', zone: '1' },
    { name: 'Tower Hill', zone: '1' },
    { name: 'Monument', zone: '1' },
    { name: 'Bank', zone: '1' },
    { name: 'Cannon Street', zone: '1' },
    { name: 'Fenchurch Street', zone: '1' },
    { name: 'Mark Lane', zone: '1' },
    { name: 'Tower Gateway', zone: '1' },
    { name: 'Aldgate', zone: '1' },
    { name: 'Liverpool Street', zone: '1' },
    { name: 'Moorgate', zone: '1' },
    { name: 'Barbican', zone: '1' },
    { name: 'Farringdon', zone: '1' },
    { name: 'Chancery Lane', zone: '1' },
    { name: 'Blackfriars', zone: '1' },
    { name: 'Temple', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Lambeth North', zone: '1' },
    { name: 'Elephant & Castle', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Oval', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Victoria', zone: '1' },
    { name: "St. James's Park", zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Temple', zone: '1' },
    { name: 'Blackfriars', zone: '1' },
    { name: 'Chancery Lane', zone: '1' },
    { name: 'Farringdon', zone: '1' },
    { name: 'Barbican', zone: '1' },
    { name: 'Moorgate', zone: '1' },
    { name: 'Liverpool Street', zone: '1' },
    { name: 'Aldgate', zone: '1' },
    { name: 'Tower Gateway', zone: '1' },
    { name: 'Mark Lane', zone: '1' },
    { name: 'Fenchurch Street', zone: '1' },
    { name: 'Cannon Street', zone: '1' },
    { name: 'Bank', zone: '1' },
    { name: 'Monument', zone: '1' },
    { name: 'Tower Hill', zone: '1' },
    { name: 'Aldgate East', zone: '1' },
    { name: 'Morden', zone: '4' },
    { name: 'South Wimbledon', zone: '3/4' },
    { name: 'Colliers Wood', zone: '3' },
    { name: 'Tooting Broadway', zone: '3' },
    { name: 'Tooting Bec', zone: '3' },
    { name: 'Balham', zone: '3' },
    { name: 'Clapham South', zone: '2/3' },
    { name: 'Clapham Common', zone: '2' },
    { name: 'Clapham North', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Oval', zone: '2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Elephant & Castle', zone: '1/2' },
    { name: 'Lambeth North', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Leicester Square', zone: '1' },
    { name: 'Tottenham Court Road', zone: '1' },
    { name: 'Goodge Street', zone: '1' },
    { name: 'Warren Street', zone: '1' },
    { name: 'Euston Square', zone: '1' },
    { name: 'Euston', zone: '1' },
    { name: "King's Cross St. Pancras", zone: '1' },
    { name: 'Angel', zone: '1' },
    { name: 'Highbury & Islington', zone: '2' },
    { name: 'Arsenal', zone: '2' },
    { name: 'Holloway Road', zone: '2' },
    { name: 'Archway', zone: '2/3' },
    { name: 'Highgate', zone: '3' },
    { name: 'Belsize Park', zone: '2' },
    { name: 'Chalk Farm', zone: '2' },
    { name: 'Camden Town', zone: '2' },
    { name: 'Mornington Crescent', zone: '2' },
    { name: 'Kentish Town', zone: '2' },
    { name: 'Tufnell Park', zone: '2' },
    { name: 'Manor House', zone: '2/3' },
    { name: 'Finsbury Park', zone: '2' },
    { name: 'Bounds Green', zone: '3/4' },
    { name: 'Woodside Park', zone: '4' },
    { name: 'West Finchley', zone: '4' },
    { name: 'Finchley Central', zone: '4' },
    { name: 'East Finchley', zone: '3' },
    { name: 'Highgate', zone: '3' },
    { name: 'Archway', zone: '2/3' },
    { name: 'Holloway Road', zone: '2' },
    { name: 'Arsenal', zone: '2' },
    { name: 'Highbury & Islington', zone: '2' },
    { name: 'Angel', zone: '1' },
    { name: "King's Cross St. Pancras", zone: '1' },
    { name: 'Euston', zone: '1' },
    { name: 'Euston Square', zone: '1' },
    { name: 'Warren Street', zone: '1' },
    { name: 'Goodge Street', zone: '1' },
    { name: 'Tottenham Court Road', zone: '1' },
    { name: 'Leicester Square', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Lambeth North', zone: '1' },
    { name: 'Elephant & Castle', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Oval', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Victoria', zone: '1' },
    { name: "St. James's Park", zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Temple', zone: '1' },
    { name: 'Blackfriars', zone: '1' },
    { name: 'Chancery Lane', zone: '1' },
    { name: 'Farringdon', zone: '1' },
    { name: 'Barbican', zone: '1' },
    { name: 'Moorgate', zone: '1' },
    { name: 'Liverpool Street', zone: '1' },
    { name: 'Old Street', zone: '1' },
    { name: 'Angel', zone: '1' },
    { name: "King's Cross St. Pancras", zone: '1' },
    { name: 'Euston', zone: '1' },
    { name: 'Euston Square', zone: '1' },
    { name: 'Warren Street', zone: '1' },
    { name: 'Goodge Street', zone: '1' },
    { name: 'Tottenham Court Road', zone: '1' },
    { name: 'Leicester Square', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Lambeth North', zone: '1' },
    { name: 'Elephant & Castle', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Oval', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Victoria', zone: '1' },
    { name: "St. James's Park", zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Temple', zone: '1' },
    { name: 'Blackfriars', zone: '1' },
    { name: 'Chancery Lane', zone: '1' },
    { name: 'Farringdon', zone: '1' },
    { name: 'Barbican', zone: '1' },
    { name: 'Moorgate', zone: '1' },
    { name: 'Liverpool Street', zone: '1' },
    { name: 'Old Street', zone: '1' },
    { name: 'Angel', zone: '1' },
    { name: "King's Cross St. Pancras", zone: '1' },
    { name: 'Euston', zone: '1' },
    { name: 'Euston Square', zone: '1' },
    { name: 'Warren Street', zone: '1' },
    { name: 'Goodge Street', zone: '1' },
    { name: 'Tottenham Court Road', zone: '1' },
    { name: 'Leicester Square', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Lambeth North', zone: '1' },
    { name: 'Elephant & Castle', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Oval', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Victoria', zone: '1' },
    { name: "St. James's Park", zone: '1' },
    { name: 'Westminster', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Temple', zone: '1' },
    { name: 'Blackfriars', zone: '1' },
    { name: 'Chancery Lane', zone: '1' },
    { name: 'Farringdon', zone: '1' },
    { name: 'Barbican', zone: '1' },
    { name: 'Moorgate', zone: '1' },
    { name: 'Liverpool Street', zone: '1' },
    { name: 'Old Street', zone: '1' },
    { name: 'Angel', zone: '1' },
    { name: "King's Cross St. Pancras", zone: '1' },
    { name: 'Euston', zone: '1' },
    { name: 'Euston Square', zone: '1' },
    { name: 'Warren Street', zone: '1' },
    { name: 'Goodge Street', zone: '1' },
    { name: 'Tottenham Court Road', zone: '1' },
    { name: 'Leicester Square', zone: '1' },
    { name: 'Charing Cross', zone: '1' },
    { name: 'Embankment', zone: '1' },
    { name: 'Waterloo', zone: '1' },
    { name: 'Lambeth North', zone: '1' },
    { name: 'Elephant & Castle', zone: '1/2' },
    { name: 'Kennington', zone: '2' },
    { name: 'Oval', zone: '2' },
    { name: 'Stockwell', zone: '2' },
    { name: 'Vauxhall', zone: '1/2' },
    { name: 'Pimlico', zone: '1' },
    { name: 'Cockfosters', zone: '5' },
    { name: 'Oakwood', zone: '5' },
    { name: 'High Barnet', zone: '5' },
    { name: 'Totteridge & Whetstone', zone: '4' },
    { name: 'Woodside Park', zone: '4' },
    { name: 'West Finchley', zone: '4' },
    { name: 'Finchley Central', zone: '4' },
    { name: 'Brent Cross', zone: '3' },
    { name: 'Golders Green', zone: '3' },
    { name: 'Hendon Central', zone: '3/4' },
    { name: 'Mill Hill East', zone: '4' },
    { name: 'Finchley Road', zone: '2' },
    { name: 'Swiss Cottage', zone: '2' },
    { name: "St. John's Wood", zone: '2' },
    { name: 'Baker Street', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Covent Garden', zone: '1' },
    { name: 'Leicester Square', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Hyde Park Corner', zone: '1' },
    { name: 'Knightsbridge', zone: '1' },
    { name: 'South Kensington', zone: '1' },
    { name: 'Gloucester Road', zone: '1' },
    { name: 'High Street Kensington', zone: '1' },
    { name: 'Earls Court', zone: '1/2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Fulham Broadway', zone: '2' },
    { name: 'Parsons Green', zone: '2' },
    { name: 'Putney Bridge', zone: '2' },
    { name: 'East Putney', zone: '2/3' },
    { name: 'Putney Bridge', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Ravenscourt Park', zone: '2' },
    { name: 'Goldhawk Road', zone: '2' },
    { name: "Shepherd's Bush Market", zone: '2' },
    { name: "Shepherd's Bush", zone: '2' },
    { name: 'Holland Park', zone: '2' },
    { name: 'Royal Oak', zone: '2' },
    { name: 'Westbourne Park', zone: '2' },
    { name: 'Ladbroke Grove', zone: '2' },
    { name: 'Latimer Road', zone: '2' },
    { name: 'Notting Hill Gate', zone: '1/2' },
    { name: "Queen's Road", zone: '1' },
    { name: 'Bayswater', zone: '1' },
    { name: 'Notting Hill Gate', zone: '1/2' },
    { name: 'Royal Oak', zone: '2' },
    { name: 'Westbourne Park', zone: '2' },
    { name: 'Ladbroke Grove', zone: '2' },
    { name: 'Latimer Road', zone: '2' },
    { name: 'Wood Lane', zone: '2' },
    { name: 'Latimer Road', zone: '2' },
    { name: 'Ladbroke Grove', zone: '2' },
    { name: 'Westbourne Park', zone: '2' },
    { name: 'Royal Oak', zone: '2' },
    { name: 'Holland Park', zone: '2' },
    { name: "Shepherd's Bush", zone: '2' },
    { name: "Shepherd's Bush Market", zone: '2' },
    { name: 'Goldhawk Road', zone: '2' },
    { name: 'Ravenscourt Park', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Hammersmith', zone: '2' },
    { name: 'Fulham Broadway', zone: '2' },
    { name: 'Barons Court', zone: '2' },
    { name: 'Earls Court', zone: '1/2' },
    { name: 'High Street Kensington', zone: '1' },
    { name: 'Gloucester Road', zone: '1' },
    { name: 'South Kensington', zone: '1' },
    { name: 'Knightsbridge', zone: '1' },
    { name: 'Hyde Park Corner', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Covent Garden', zone: '1' },
    { name: 'Leicester Square', zone: '1' },
    { name: 'Piccadilly Circus', zone: '1' },
    { name: 'Green Park', zone: '1' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Baker Street', zone: '1' },
    { name: "St. John's Wood", zone: '2' },
    { name: 'Swiss Cottage', zone: '2' },
    { name: 'Finchley Road', zone: '2' },
    { name: 'Mill Hill East', zone: '4' },
    { name: 'Hendon Central', zone: '3/4' },
    { name: 'Golders Green', zone: '3' },
    { name: 'Brent Cross', zone: '3' },
    { name: 'Finchley Central', zone: '4' },
    { name: 'West Finchley', zone: '4' },
    { name: 'Woodside Park', zone: '4' },
    { name: 'Totteridge & Whetstone', zone: '4' },
    { name: 'High Barnet', zone: '5' },
    { name: 'Oakwood', zone: '5' },
    { name: 'Cockfosters', zone: '5' },
    { name: 'Hatton Cross', zone: '5/6' },
    { name: 'Heathrow Terminals 2 & 3', zone: '6' },
    { name: 'Heathrow Terminal 4', zone: '6' },
    { name: 'Heathrow Terminal 5', zone: '6' },
    { name: 'Abbey Wood', zone: '4' },
    { name: 'Acton Main Line', zone: '3' },
    { name: 'Bond Street', zone: '1' },
    { name: 'Brentwood', zone: '9' },
    { name: 'Canary Wharf', zone: '2' },
    { name: 'Custom House', zone: '3' },
    { name: 'Ealing Broadway', zone: '3' },
    { name: 'Farringdon', zone: '1' },
    { name: 'Forest Gate', zone: '3/4' },
    { name: 'Gidea Park', zone: '6' },
    { name: 'Goodmayes', zone: '4' },
    { name: 'Hanwell', zone: '4' },
    { name: 'Harold Wood', zone: '6' },
    { name: 'Hayes & Harlington', zone: '5' },
    { name: 'Heathrow Terminal 2 & 3', zone: '6' },
    { name: 'Heathrow Terminal 4', zone: '6' },
    { name: 'Heathrow Terminal 5', zone: '6' },
    { name: 'Ilford', zone: '4' },
    { name: 'Iver', zone: '7' },
    { name: 'Langley', zone: '6' },
    { name: 'Liverpool Street', zone: '1' },
    { name: 'Maidenhead', zone: '9' },
    { name: 'Manor Park', zone: '3/4' },
    { name: 'Maryland', zone: '3' },
    { name: 'Paddington', zone: '1' },
    { name: 'Reading', zone: 'Special' },
    { name: 'Romford', zone: '6' },
    { name: 'Seven Kings', zone: '4' },
    { name: 'Shenfield', zone: '9' },
    { name: 'Slough', zone: '6' },
    { name: 'Southall', zone: '4' },
    { name: 'Stratford', zone: '2/3' },
    { name: 'Taplow', zone: '8' },
    { name: 'Twyford', zone: 'Special' },
    { name: 'West Drayton', zone: '6' },
    { name: 'West Ealing', zone: '3' },
    { name: 'Whitechapel', zone: '2' },
    { name: 'Woolwich', zone: '4' },
];
